### ISSUE TITLE
[Transport protocol] Announce available content-type 

### ISSUE THREAD

**Issue by tiero** [tdex-network/tdex-daemon#190]

**Comment by altafan** [comment]
@sekulicd Once [#51](https://github.com/tdex-network/tdex-protobuf/issues/51) is done, we can add here a new handler implementing the TransportService interface of the stub. For now, the handler must return every content-type specified in the proto but JSON.

The handler doesn't need any underlying app service. This is something related only to the interface layer and doesn't require any other lower level as dependency.

The related grpc interface must be always reachable. The grpc service contains logic to enable the operator and the trade interfaces only after the internal wallet is unlocked. The transport interface doesn't care about the internal status of the daemon at all and must be always enabled at its very start-up, and stopped only when the daemon is switched off.
