### ISSUE TITLE
Add DropMarket RPC

### ISSUE THREAD

**Issue by tiero** [TDex-network/tdex-daemon#281]
Sometimes it coudl happen to create a new market by mistake (ie. calling DepositMarket RPC w/o arguments). This makes the crawler to watch that address for deposits and until it's not done, it will log warning in the logs whihc is annoying. 

There shoudl be a way to drop this market (if not funded the first time could be a nice check, altough no-one prevent us to drop already funded market anyway)

**Comment by sekulicd** [comment]
@tiero is this still valid considering we are no longer 'observe' addresses?

**Comment by tiero** [comment]
We do not observe addresses anymore that's true, but we may want to drop a market that is never claimed maybe? But I agree that now becomes less priority, will keep in hold
