### ISSUE TITLE
Investigate overconsumption of CPU with latest master

### ISSUE THREAD

**Issue by tiero** [TDex-network/tdex-daemon#287]
You can see the change in the CPU consumption just switching from commit `b3965b316a5ed37fe5ff53781dc9db6a254e34b3` to `0ab84f87237a1023258401d8e0d168f4ef59bcc9`

I tried to "drop" only that commit (ie. `git revert --strategy resolve 0ab84f87237a1023258401d8e0d168f4ef59bcc9`), but every subsequent commit is too tangled to that, so would be better to inverstigate how to make it less expensive.

https://github.com/golang/go/issues/27707
https://stackoverflow.com/questions/55367231/golang-for-select-loop-consumes-100-of-cpu

I suspect time.Sleep introdcued in the for loop is not the best strategy here

**Comment by tiero** [comment]
instead of "sleeping" before inserting an observable, would be better to attach specific options to each observable that will dictate the behavior ie. when to trigger. In #276 we introduce this topic better and I think that would be the definitive solution.

**Comment by tiero** [comment]
## Daemon "empty" just started 

![image](https://user-images.githubusercontent.com/3596602/110179565-8ddf6c80-7e08-11eb-823f-8377136995d8.png)


## Daemon after funding and opening a market 

![image](https://user-images.githubusercontent.com/3596602/110179645-b9faed80-7e08-11eb-97d9-72718466b2c7.png)

**Comment by tiero** [comment]
# Commit hash `b3965b316a5ed37fe5ff53781dc9db6a254e34b3` 

## empty

![image](https://user-images.githubusercontent.com/3596602/110179946-3392db80-7e09-11eb-851b-840e9447c4f3.png)


## funded market

![image](https://user-images.githubusercontent.com/3596602/110180012-57eeb800-7e09-11eb-9935-0093ab9d3ebd.png)

**Comment by tiero** [comment]
Don't ask me why, following this [comment](https://github.com/golang/go/issues/27707#issuecomment-698487427)

Adding this microsecond of sleep in `listenToEventChannel` in `blockchain_listener` visibly lowered the "noise" my computer was doing. I don't have much experience on how to "demonstrate" this with `pprof` (cc/ @sekulicd) but pretty sure this is the problem in there.

**Comment by tiero** [comment]
On a amazon ec2 the `v0.2.0-rc.2` was eating 100% of container CPU all the time

Now with the latest we have a variable consumption that goes from 0.74% to max 34%. I suspect that those spikes are the ticker calling the explorer, so this makes sense.

**Comment by sekulicd** [comment]
@tiero u can check CPU profile by doing as follows:
1. go tool pprof http://localhost:8024/debug/pprof/profile\?seconds\=30 -> this will profile CPU for 30 sec, do this after some time when u hear the noise.
2. after profiling finishes type 'web' and u should see image with most intensive method calls

Another way: 
1. go tool pprof http://localhost:8024/debug/pprof/profile\?seconds\=30
2. in ~/pprof it should be generated profile file 
3. Then u run go tool pprof -http :8080 {cpu file} -> in my case name was pprof.samples.cpu.001.pb.gz 

Please find attachment of CPU profile that i did if u dont want to bother.
![profile001](https://user-images.githubusercontent.com/1805417/110201399-24d91280-7e63-11eb-9395-a1220a1661c8.png)

In picture u can see that unblindingUtxo method is 'killing' us, more precisely confidential.UnblindOutputWithKey.
Before when we had one ticker, which by default was set to 5000(5sec) we would crawl all addresses async and do unblinding and then CPU would relax, now we have ticker for each address and we constantly fetch and unblind which makes CPU work all the time. RateLImiter helps in a way that is limits to 10 calls in second(as per current configuration).

**Comment by tiero** [comment]
Closing, altough we may need to lowere the depenedency on many cgo calls @altafan
