### ISSUE TITLE
[Proposal] Re-think the deposit design to not depend on blockchain polling

### ISSUE THREAD

**Issue by tiero** [TDex-network/tdex-daemon#293]
This is a competing idea with other that go in the line to increase the reliability of the daemon, which is not stable yet 

## Issues:

- Balances are not always in sync https://github.com/TDex-network/tdex-daemon/issues/289
- Maybe this also due crawling mechanics https://github.com/TDex-network/tdex-daemon/issues/290
- High CPU usage (partly due the handleUnspents) https://github.com/TDex-network/tdex-daemon/issues/287

## Competing proposals

- [Blockchain data fetching] Proposal: Expect external service to notify daemon about wallet activites  https://github.com/TDex-network/tdex-daemon/issues/260

Not entirely a drop-in alternative, but if #260 gets traction and is the way to go, the curren crawler + blockchain listener will be detached by the tdex-daemon, but eventually suffer from the same problem I guess (unless we discover that balances problems are due internal repositories, rather than actual blockchain polling)

- Smarter request throttling  https://github.com/TDex-network/tdex-daemon/issues/276

This would not need any more throttling

### TL;DR

Expect end user to "claim" deposits instead of observing addresses returned via RPC and update internal unspents view only at startup and after a "write" (ie. a Trade or a Witdrawal)

### Long (?) story

We need to keep a view of the unspents of the wallet in order to: 

- accept trades automatically with minimal latency
- serve Balances endpoint for the traders to know about reserves
- Eventually log operator about low balance for a market or the fee account

At the moment we have in place polling activity ie. every 5 seconds to know about if wallet state is changed. Altough we could increase to 1 min (Liquid block time), we would loose reponsiveness for future trades, halt concurrent trading for too long and as per curren deposit mechanics we would wait too much to fund a market.

To lower the polling activity we could assume the wallet state changes:

a) after a Trade succesful
b) after a Witdrawal 
c) after a new deposit
d) external wallet softawre using the same mnemonic (Is that necessary?)

- Excluding `d` wich def need polling, we could accomplish a-c without involing any blockchain polling:
- For `a` and `b` we update the internal cache right away with internal data after tx got broadcasted. We could make extra call (non blocking in async) to go check if something wrong, but this is just we are paranoid.
- For `c` the idea is to change the current RPC flow for the operator in a way is his duty to call an additional RPC ie. `ClaimDeposit` passing us txid(s) in a way we could go check to the chain when requested if the deposit is there and got confirmations. We could even asks for vout, this will also indicate from the operator wich market is wich (ie no inference)

### Motivation

Looking at the actual operations of a Liquidity Provider, the process to deposit is quite involving already and needs some dedication: a) source funds b) fragment them c) ask for and address and make push the transaction
Asking the LP to do an extra step to proivde us proof of the deposit, I see it not that more demanding. Also is something you do with max focus most of the time, you are going to have few moments of deposit, in not something frequent or casual activity.

### FAQ

TBD

 
﻿

**Comment by tiero** [comment]
Please read it and evaluate when you got time @sekulicd @altafan @louisinger

**Comment by altafan** [comment]
> * [Blockchain data fetching] Proposal: Expect external service to notify daemon about wallet activites #260

Yeah, I don't see this as a complete alternative.  I think #260 is something that the daemon needs to focus only on its main purpose, which is allowing to trade asset pairs.

The 2 proposals could co-exist IMO: we could have the daemon updating its cache for a)-c) as you described, while an external notify service to cover d) edge case essentially. I mean, I would expect the external crawler to notify also unspents for a)-c), but it shouldn't difficult to "ignore" those events.

Question:
Is there the chance to increase the possibility of transactions conflicts when processing trades with this proposal?

**Comment by tiero** [comment]
> Question:
> Is there the chance to increase the possibility of transactions conflicts when processing trades with this proposal?

Not anymore than now, especially if we move to #279, but even w/o that we would have LESS concurrent writes since will be limited only at deposit, withdrawal and trade time, where we have plenty of time to retry until it works.

**Comment by sekulicd** [comment]
I still think that Crawler can do it :), we just need to tune it with:
1. Best Crawl interval
2. Exponential back off for inactive addresses 
3. Maybe number of allowed addresses
4. Maybe mix of crawling and relaying on operators info(proposal u mentioned from a-c)
5. Maybe mixing ZMQ and polling 

Important part would be to know exact limitation with external API(elements/esplora), ie. num of calls per second.

With current solution we are only sure that CPU usage is issue(for #289 and #290 we are still not sure), where we identified:
1. UnblindOutputWithKey as CPU intensive
2. Most probably having ticker for each address is also problem for CPU (considering that num of addresses can increase)

Ofcourse it would better if we could lower the load with lower number of calls to external explorer by watching internal state and forcing operator to 'ClaimDeposit'.
For a) and c) it would be enough to check max few times if TX is confirmed.
As for b) and d) assumption is that this wont happen frequent and we could leave responsibility to the operator to 'inform' daemon about those events.

Replacing crawler with messaging system, mentioned in #260, sounds like good idea but i dont know about ZMQ performance, limitations, latency in order to judge.

**Comment by tiero** [comment]
> I still think that Crawler can do it :), we just need to tune it with

As I answered in #260 I do not want to "drop" the crawler, rather that detaching for having a better separations of concern and potential re-use the crawler accross many different daemons (ie. Kubernetes deployment etc..)

So all the improvemente proposed will definitely be needed, my proposal is to chnage the flow, to lower the strong dependency on having a "real-time" view of the utxo set.

**Comment by louisinger** [comment]
> Excluding d wich def need polling, we could accomplish a-c without involving any blockchain polling:

if `d` (i.e non-daemon wallet activities) needs polling, I don't really see how do you reduce the number of requests? I'm thinking about the following example:
1- Provider deposits funds on market address **A0** (1 utxo with 1 LBTC). 
2- The provider withdraws 0.5 LBTC _using the daemon_.
3- 2 seconds later the provider moves (_manually or using another app_) 0.8 BTC.

If we want the utxo set to be representative of the current wallet state: we need to poll the blockchain for `A0` to know what withdrawal transaction (2 or 3) has been confirmed first.

> For a and b we update the internal cache right away with internal data after tx got broadcasted. We could make extra call (non blocking in async) to go check if something wrong, but this is just we are paranoid.

this "extra call" seems to be mandatory. We can't serve trades using the newly created utxos if something wrong happens, isn't it?

**Comment by tiero** [comment]
> (manually or using another app)

i do think this is not something we should encourage and make clear is not allowed. Also the derivation path is custom and makes not a common wallet seed to be portable accross implementations

To allow graceful handling of these scenario, with the same pricinple of the claim deposit, we can add an RPC that operator can call to reload utxo set, which can be helpful anyway in other scenarios.

> newly created utxos if something wrong happens

We update the internal utxo set (or unlock in failure cases) only if the txid we know about got 1 confirmation. So yes, we still observe txs after trades are completed actually, maybe wasnt clear.

The extra (non blocking) call is about to go check if that script owns the same unspents, but agaim, if txid:vout we got block confirmation there in 0 reason why shouldnt be.

Reorg could be a topic in Bitcoin, but not in Liquid, 2 block confirms means finality
