### ISSUE TITLE
Add ClaimMarketDeposit  to create a new market  and ClaimFeeDeposit RPCswith to fund the fee account

### ISSUE THREAD

**Issue by tiero** [TDex-network/tdex-daemon#296]
## proto spec

```proto
service Operator {
	// Operator can provide transaction(s) outpoints of deposits made to create a new market.
	// The transaction must be visible and confirmed, otherwise an error will be returned,
	// inviting the operator to retry again
	rpc ClaimMarketDeposit(ClaimMarketDepositRequest) returns (ClaimMarketDepositReply)
	rp ClaimFeeDeposit(ClaimFeeDepositRequest) returns (ClaimFeeDepositReply)
}

message ClaimMarketRequest {
	Market market = 1; // this may or may not exists already. Use DropMarket to delete an unclaimed market
	repeated TxOutpoint outpoints = 2; //list of tx outpoints with deposit outputs. If many vout in the same transaction, the tx hash will be repeated
}

message TxOutpoint {
	string tx_hash = 1;
	int32 index = 2;	
}

message ClaimMarketReply {}

message ClaimFeeDepositRequest {
        repeated TxOutpoint outpoints = 1; //list of tx outpoints with deposit outputs. If many vout in the same transaction, the tx hash will be repeated
}
message ClaimFeeDepositReply {}
```

## Logic

These RPCs will trigger the daemon to go check those provided transactions and to recognize if the given outpoint are locked on addresses/scripts owned by the daemon. If this validation goes through, it will not return error and will in async way go update the spentness of the utxo set #298 decoding the transactions hexes

**Comment by altafan** [comment]
> These RPCs will trigger the daemon to go check those provided transactions and to recognize if the given outpoint are locked on addresses/scripts owned by the daemon. If this validation goes through, it will not return error and will in async way go update the spentness of the utxo set #298 decoding the transactions hexes

I go confused by this logic... from what I understood in the original proposal, ClaimMarketDeposit and ClaimFeeDeposit RPCs should basically allow the operator to notice the daemon that some unspents are actually funds of a certain market and they need to be added to the storage.

I'm ok with checking if these unspents are already in the storage to prevent having doubles accidentally, but I don't get why we should update their spentness once inserted.

Is it possible that you have just mixed concepts of WithdrawMarkets/TradeComplete with those of ClaimMarket/FeeDeposit??

**Comment by tiero** [comment]
> but I don't get why we should update their spentness once inserted.

update their spentness == add unpent to storage

I take `spentness` from https://github.com/btcsuite/btcwallet/blob/master/rpc/documentation/api.md#spentnessnotifications to talk both about new unspent and to "mark as spent an unspent" (because is terrible to say). Spenteness means both in asingle word
