### ISSUE TITLE
Prevent RPCs to return sensitive data if wallet is locked

### ISSUE THREAD

**Issue by altafan** [TDex-network/tdex-daemon#321]
There are many RPCs like ListMarket (the very first one that I noticed, the complete list will follow) that I guess they shouldn't do anything but returning an error in case the wallet hasn't been unlocked yet.
In every of these RPCs, after validating the eventual arguments, we should retrieve the vault and check is it's still locked and return an error just in case.

I wonder if we could create a kind of middleware to avoid having repetion of code.

**Comment by altafan** [comment]
Wallet service RPCs are ok.

The only available RPC of the trader service is Markets but I guess this might be ok. At interface level, we should "rename" the error to something more meaningful for the trader like `service not reachable` or something like that instead of the chanonical `wallet must be unlocked to perform this operation`.

Basically none of the operator service's RPCs are ok at the moment.
This is the list of completely unsafe RPCs, ie. those that do their job data even if the wallet is locked:
1. `ListMarket`
2. `UpdateMarketFee`
3. `UpdateMarketStrategy` 
4. `ListSwaps`
5. `ReportMarketFee`
6. `ReloadUtxos`
7. `ListUtxos`
8. `DropMarket`

The other ones might seem ok but just because at a certain point they use the internal _vault_ which errors because it's still locked. This means that all the other operations made before involving the _vault_ can potentially cause changes to other domains/repositories unexpectedly.

In general, checking the status of the _vault_ should be the very first thing to do (before or after validating the eventual arguments?) in order to prevent unexpected behaviors later in the future.

**Comment by tiero** [comment]
We can close it?
