### ISSUE TITLE
[Webhook] Notify for fee/market account low balance

### ISSUE THREAD

**Issue by altafan** [TDex-network/tdex-daemon#365]
Originally, the blockchain listener was responsible, among other things, to watch for the balance of the fee or market account and notify the operator via a warning message on stdout in case the balance was too low.
That service doesn't have such responsibility anymore, and at the moment, the daemon checks only for zero balance into MarketPrice and TradePropose RPCs.

Is it necessary to add some kind of balance threshold under which the daemon denies previews/trades?

**Comment by tiero** [comment]
I do think we already return error in preview/trades.

What we can do is to trigger an action webhook to notify via email about this.
