### ISSUE TITLE
Refactor preview

### ISSUE THREAD

**Issue by altafan** [TDex-network/tdex-daemon#368]
At the moment it is hard to unit test previews for markets. All the logic relative to what kind of preview to make based on the market strategy etc resides in the application layer, but we do want to have only component tests at that level.

My proposal is to add a `Preview()` method (args TBD) to the market domain, where to basically move all the logic currently living in trade_service.go, with the purpose of streamlining the code of the app layer to just a function call.

It is true that such method would not change the internal state of the domain so technically should not be part of it, but it's also true that a preview is strictly related to a market (the only "external" data are its balances).
The PROs, to me, are evident:
* Changes at domain level, like for example adding a strategy, would not require changes at app level, like creating an internal function for calculating previews for that specific strategy.
* we would be able to write unit test of previews for all kind of strategies, making it easier to find&fix bugs such as #366 in the future.

@tiero @sekulicd @louisinger do you have any feedback?

**Comment by sekulicd** [comment]
@altafan do u want to test [this](https://github.com/TDex-network/tdex-daemon/blob/1bfb0312f255078835cf41cc44dcb1980309267e/internal/core/application/trade_service.go#L861) method?

**Comment by altafan** [comment]
@sekulicd Exactly. To be super clear, I want to unit test it. And I want also to move that function and all those related down to the domain level to accomplish unit testing.

**Comment by sekulicd** [comment]
I think it make sense to move it to domain or you can just export 'previewForMarket' method and unit test it in app layer.

**Comment by altafan** [comment]
As already said in the very first comment, we do want only component tests in app layer. Exporting the method would be fine, but, again, as already said the actual design implies that changes to the market domain require changes also at app level and this is not good for maintainability/scalability.

**Comment by tiero** [comment]
We still having bugs in calculation in the MarketPrice
