### ISSUE TITLE
Creation of Operator TLS cert/key needs to be fixed?

### ISSUE THREAD

**Issue by altafan** [TDex-network/tdex-daemon#377]
I started using the newest version v0.4.0-rc.2, and I noticed something about the creation of a TLS key/cert for the Operator interface.
In my opinion, it would be nice if the daemon managed the creation of the TLS cert/key file following these criteria:
1. if there are not key/cert files both must be created
2. if both already exist nothing needs to be done
3. if only the key.pem file exists, a new cert.pem must be created
4a. if only the cert.pem exists, then it's deleted and a new pair is created
4b. if only the cert.pem exisits an error is returned suggesting to delete the certificate

At the moment, only 1 and 2 options are supported and if only one out of the key and the cert exist an error is returned.
Is this the best behavior? Shall we support 3 and one between 4a and 4b?

cc @tiero.

**Comment by tiero** [comment]
3 adn 4b
