### ISSUE TITLE
Cert issues when following docker instructions

### ISSUE THREAD

**Issue by asoltys** [TDex-network/tdex-daemon#399]
I built and ran docker image using the commands in the README:

```
docker build --pull --rm -f "Dockerfile" -t tdexd:latest "."
docker run -d -it --name tdexd -p 9945:9945 -p 9000:9000 -v `pwd`/tdexd:/.tdex-daemon tdexd:latest
alias tdex="docker exec -it tdexd tdex"
```

First issue was to do with the volume mount path:

```
tdex init                                                                                                                            
[tdex] could not read TLS certificate:  open /root/.tdex-daemon/tls/cert.pem: no such file or directory
```

Changing the run command to mount to /root/.tdex-daemon instead of /.tdex-daemon seemed to help:

`docker run -d -it --name tdexd -p 9945:9945 -p 9000:9000 -v `pwd`/tdexd:/root/.tdex-daemon tdexd:latest`

But then I get a message about the unsigned cert:

```
tdex init
[tdex] rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority"
```

Running into the same issues when trying to use tdex-box

**Comment by tiero** [comment]
`tdex init` should be `tdex config init`

**Comment by asoltys** [comment]
Also tried

`tdex config set no_macaroons true`

But then get:

`tdex init
[tdex] rpc error: code = Unavailable desc = connection closed`

**Comment by altafan** [comment]
Hi @asoltys,

after starting up the daemon with the first command you mentioned, you need to confugure the cli with:
```sh
$ tdex config init --macaroons_path /.tdex-daemon/macaroons/admin.macaroon --tls_cert_path /.tdex-daemon/tls/cert.pem
```

At the moment, by default the CLI uses the path `/root/.tdex-daemon` instead of /.tdex-daemon` to source macaroons and TLS certificate, which is something that needs to be addressed.

But you should be fine by running the command above.

**Comment by tiero** [comment]
that being said we should make sure the datadir is always the $HOME so the embedded CLI can automatically discover the macaroons and the TLS self signed certificate.

Also we should drop the `tdex config init` step which is confusing #341 and use sane defaults to start with

**Comment by asoltys** [comment]
Thanks guys yeah specifying the paths like that did the trick

**Comment by altafan** [comment]
> Also tried
>
> tdex config set no_macaroons true

This doesn't work because you are starting the daemon with macaroons auth. To make it work you need to add a `-e TDEX_NO_MACAROONS=true` to your daemon's start command in order to disable the auth machinery which is enabled by default.

**Comment by asoltys** [comment]
Hmm now with TDEX_NO_MACAROONS=true I get:

tdex genseed
[tdex] rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: read tcp 127.0.0.1:42732->127.0.0.1:9000: read: connection reset by peer"

**Comment by asoltys** [comment]
If I leave macaroons enabled, I can genseed, but then can't listmarket:

```
tdex listmarket
[tdex] could not read macaroon /.tdex-daemon/macaroons/admin.macaroon: open /.tdex-daemon/macaroons/admin.macaroon: no such file or directory
```

**Comment by altafan** [comment]
Did you configure the CLI with `tdex config set no_macaroons true`?

**Comment by asoltys** [comment]
At one point I did but I removed the whole tdexd/ folder and re-ran the image with NO_MACAROONS commented out. It recreates the folder but macaroons/ is empty

**Comment by altafan** [comment]
Yeah, that's the expected behavior of the daemon. In case it runs wo/ macaroons auth, it doesn't create any macaroon file or TLS certificate because it just won't use them.

Therefore, you need to confugure your CLI to work without macaroons with `tdex config init --no_macaroons` (or `tdex config set no_macaroons true` if you already configured it the first time) so it knows it doesn't need to source any file at macaroons_path or tls_cert_path.

**Comment by asoltys** [comment]
I'm trying to run it with macaroon auth enabled now though, i.e. with the TDEX_NO_MACAROONS variable commented out or set to false, but it's not generating an admin.macaroon for me

If I run without macaroons, I get this:

```
tdex genseed
[tdex] rpc error: code = Unavailable desc = connection closed
```

**Comment by altafan** [comment]
Sorry @asoltys  I misread your comment, I was thinking you were sill in the no macaroons mode.

So, if you are running with macaroons auth again, all mac files are created when `init`ing or `unlock`ing the daemon's wallet.
Evenmore, no commands but `genseed`, `init` and `unlock` will work until you have initialized your daemon .

So after `genseed` try to call `tdex init --password <yourpassword> --seed "<genseed_output>"`

**Comment by asoltys** [comment]
tdex init --seed sun action erosion duty onion apology destroy breeze switch draft notice dice exist critic rough vivid rifle chalk keen injury among price critic tonight --password password
[tdex] rpc error: code = InvalidArgument desc = mnemonic is null

**Comment by asoltys** [comment]
Nevermind, just had to put the seed in double quotes
