### ISSUE TITLE
Do not assume the Market Base asset is L-BTC

### ISSUE THREAD

**Issue by tiero** [tdex-network/tdex-daemon#408]
It can happen that a market's base asset happens to be something like a stablecoin or other asset that can't be used to pay for transaction fees. At the moment we assume that, ie. `operatorService` should have a parameter to know the asset hash of the blockchain used to pay for transaction fees

**Comment by tiero** [comment]
Also, we should have an ENV VAR dedicated for the LBTC asset hash. Ij regetst we discovered with @Janaka-Steph that if we change the fedpegacript also the LBTC asset hash will.change.

Would be handy to have `TDEX_NATIVE_ASSET_HASH` env var. If not set we will use the AssetID of the network struct passed

**Comment by sekulicd** [comment]
> Ij regetst we discovered with @Janaka-Steph that if we change the fedpegacript also the LBTC asset hash will.change.

We are using LBTC asset hash in fee outputs from [network](https://github.com/vulpemventures/go-elements/blob/521a5fc29d945e073e6f676d01c172d11ecf978b/network/network.go#L52) pkg of go-elements
and if above is true we have issue with network pkg itself.

**Comment by tiero** [comment]
Yes the idea is to have a way to choose which is the asset hash used for fees, without default looking at the hardcoded one in Regtest struct in network pkg.

In mainnet is not a problem, but very useful for testing.
