### ISSUE TITLE
WithdrawMarket RPC: failed to recover information about author of range proof

### ISSUE THREAD

**Issue by tiero** [tdex-network/tdex-daemon#409]
I am trying to withdraw from a funded market and I got this error `"2 UNKNOWN: failed to recover information about author of range proof"`

My `WithdrawMarket` request payload

```json
{
  "market": {
    "base_asset": "5ac9f65c0efcc4775e0baec4ec03abdde22473cd3cf33c0419ca290e0751b225",
    "quote_asset": "cba679e5ad472447cb26236c2a7d58198b334770ebcffefb5fbba9e6463e9b1e"
  },
  "balance_to_withdraw": {
    "base_amount": 100,
    "quote_amount": 100
  },
  "millisat_per_byte": 1000,
  "address": "el1qqtaa843j80v9tthju77ul7m385e429dafwqmcvsq9yqt7ucl0ku2fxzgtwwdsr2trwuuzuwukd9jvqxy5c4zcyzvht5y30ca6",
  "push": false
}
```

My `Balances`

```
{
  "balances": [
    {
      "balance": {
        "base_amount": "1000",
        "quote_amount": "100000000"
      },
      "fee": {
        "basis_point": "0",
        "fixed": {
          "base_fee": "650",
          "quote_fee": "1"
        }
      }
    }
  ]
}
```

My `ListMarket`

```
{
  "markets": [
    {
      "market": {
        "base_asset": "5ac9f65c0efcc4775e0baec4ec03abdde22473cd3cf33c0419ca290e0751b225",
        "quote_asset": "cba679e5ad472447cb26236c2a7d58198b334770ebcffefb5fbba9e6463e9b1e"
      },
      "fee": {
        "basis_point": "0",
        "fixed": {
          "base_fee": "650",
          "quote_fee": "1"
        }
      },
      "tradable": false,
      "account_index": "5",
      "price": {
        "base_price": 0.0008500000112690032,
        "quote_price": 1200
      }
    }
  ]
}
```

**Comment by sekulicd** [comment]
It fails in go-elements, specifically in RangeProofRewind method which is invoked in UnblindOutput(go-elements), which is eventually called by WithdrawMarketFunds method of the operator.
It looks like an issue with blinding keys.
I am not able to give more precise analysis since i am not able to reproduce the issue.

**Comment by tiero** [comment]
So you can spinup a tdexd, fund a market and withdraw funds from it?

Can we add a test case eventually?

**Comment by altafan** [comment]
Hmm that's unexpected.. no range or surjection proofs are stored by the daemone, the blinding factor and revealed asset/amount do instead.

The pkg/wallet methods should work with blinders instead of blinding keys because of what pointed above.

**Comment by sekulicd** [comment]
> So you can spinup a tdexd, fund a market and withdraw funds from it?

Yes I managed to reproduce it.

Here is the stack trace:
<img width="921" alt="Screenshot 2021-08-21 at 10 06 16" src="https://user-images.githubusercontent.com/1805417/130315387-6b9e62da-fb8c-4409-81ce-d99323703733.png">

**Comment by tiero** [comment]
to be clear, you DO NOT have this error?

**Comment by sekulicd** [comment]
> to be clear, you DO NOT have this error?

Yes I have, I managed to reproduce it as said in last comment.
