### ISSUE TITLE
Slice initialisation issue

### ISSUE THREAD

**Issue by sekulicd** [tdex-network/tdex-daemon#411]
Check slice init in [here](https://github.com/tdex-network/tdex-daemon/blob/70d50a8b72a45fbb78e2eb8bd428438090230f88/internal/core/application/operator_service.go#L1101)

This can lead to various bugs, since we are creating slice which length is not 0 but it is populated with empty structs.
Imagine ranging over this kind of slice and inserting in DB empty structs.

Maybe at this exact place we wont have bug but in general IMHO if we know (for sure) how many elements slice will have we should initialise like `make([]someSlice, 0, len(known_num))`

@tiero @altafan thoughts ?

**Comment by altafan** [comment]
This is definitely a left-over. Totally agree on the suggested change. You can include this in #412 if you want.

**Comment by tiero** [comment]
Is it fixed? @sekulicd @altafan

**Comment by sekulicd** [comment]
> Is it fixed? @sekulicd @altafan

Not yet,  assigning it to my self.
