### ISSUE TITLE
TLS: Specify all the cipher suite in sane order

### ISSUE THREAD

**Issue by tiero** [tdex-network/tdex-daemon#418]
Like this commit https://github.com/tdex-network/tor-proxy/commit/871d014533fa1453b0d10ce30396bff8fd8c14f0

**Comment by altafan** [comment]
@tiero are you suggesting to replace this [line](../blob/master/internal/interfaces/grpc/http_utils.go#L200) with:
```
requiredCipher := []uint16{
	tls.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
	tls.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
	tls.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,
	tls.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,
	tls.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,
	tls.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,
	tls.TLS_RSA_WITH_AES_128_CBC_SHA,
	tls.TLS_RSA_WITH_AES_256_CBC_SHA,
}
```
?

**Comment by tiero** [comment]
Yes, https://github.com/tdex-network/tor-proxy/blob/master/pkg/torproxy/torproxy.go#L122-L132

**Comment by tiero** [comment]
I suspect this error that happens in browser is linked to this https://github.com/tdex-network/tdex-app/issues/302
