### ISSUE TITLE
Pluggable: BasePrice and QuotePrice can be less than zero

### ISSUE THREAD

**Issue by tiero** [tdex-network/tdex-daemon#456]
In this commit we introduced a validation check on the Price domain https://github.com/tdex-network/tdex-daemon/commit/ebfe465a1c8b5f111385a7383d55f475e94f6a35#diff-4d41ed4b84fbbf1a8d096677eb4767a6976b057cfa37f81e89111b502a488390R126-R131 that is conceptually wrong: the prices can def be less than zero

**Comment by tiero** [comment]
We should check instead they are at least one satoshi tho

**Comment by altafan** [comment]
Closed by #457.
