### ISSUE TITLE
Allow to specify asset to withdraw in WIthdrawFee RPC

### ISSUE THREAD

**Issue by altafan** [tdex-network/tdex-daemon#459]
It could happen that someone deposits funds of some other type of asset rather than LBTC to the fee account.

The daemon cannot do anything but storing info about that/those utxo(s) and printing a warning on stdout suggesting to withdraw these funds ASAP.

Given this, I think we should allow the operator to explicitly specify the asset to withdraw for the fee account in the request. At the moment, there's no asset filed into the incoming request and the daemon always work with LBTCs.

@tiero do you agree?

**Comment by tiero** [comment]
Yes, this can be helpful. I would make sure that by default is LBTC if the field is empty.

**Comment by altafan** [comment]
Closed by #462.
