### ISSUE TITLE
Release: Support ARM64 darwin/linux

### ISSUE THREAD

**Issue by tiero** [tdex-network/tdex-daemon#483]

**Comment by jwaugh** [comment]
This would be great!

Tried running docker container, but had no luck.

docker run -it -d --name tdexd --restart unless-stopped -p 9945:9945 -p 9000:9000 -v `pwd`/tdexd:/.tdex-daemon ghcr.io/tdex-network/tdexd:v0.7.0-arm.0
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
cc0805bc660a816cfb4d4ec602c8c6d75a98e1557007e6720f2eec38e9fe3b0f

**Comment by tiero** [comment]
Not in master yet and that docker tag is only a pre-release, so you have been very brave :) Working on it

That being said, if you type `docker logs tdexd` what gives to you? If you using Apple Silicon M1 with rosetta AFAIK it should be able to emulate it, using the amd64 version

**Comment by tiero** [comment]
This pre-release should have the right docker image for arm architectures https://github.com/tdex-network/tdex-daemon/releases/tag/v0.7.0-arm.1
