### ISSUE TITLE
[UnlockWallet] Proposal: always return error if passphrase not correct

### ISSUE THREAD

**Issue by Janaka-Steph** [tdex-network/tdex-daemon#487]
If passphrase is not correct but wallet is already unlocked, UnlockWallet is not returning error 'passphrase provided is not correct'.
From UI, to circumvent this I have to check IsReady before calling UnlockWallet.
Proposal: Always return error 'passphrase provided is not correct' if passphrase is not correct.
Or return error 'Wallet is already unlocked' if wallet is already unlocked, not checking passphrase validity.

**Comment by tiero** [comment]
What now is returned instead? 

I think is normal to call `isReady` as first thing, to decide to either initialize or to unlock.

**Comment by Janaka-Steph** [comment]
If wallet is already unlocked but passphrase is wrong, empty object is returned, no error. 
It works also fine to call isReady before UnlockWallet.
