### ISSUE TITLE
[UpdateMarketPercentageFee] Does not handle decimal values

### ISSUE THREAD

**Issue by Janaka-Steph** [tdex-network/tdex-daemon#496]
UpdateMarketPercentageFee does not handle decimal values, only retaining integer part.
For example, calling it with basis_point = 12.8, only the integer part 12 is saved.

**Comment by altafan** [comment]
The percentage must be expressed in basis point, hence values between [0, 9999]. `12.8` is equal to `1280` for example.
Closing.
