### ISSUE TITLE
Add gRPC call to retrieve MarketInfo of a specific market

### ISSUE THREAD

**Issue by Janaka-Steph** [tdex-network/tdex-daemon#498]
Currently the only way to retrieve MarketInfo is to call ListMarkets then filter.

**Comment by Janaka-Steph** [comment]
And/or NewMarketReply could return marketInfo.

**Comment by tiero** [comment]
with these change (new RPC for fetching single market infos and returning it in NewMarketReply) to operator we can tag the v0.8 for EOW @altafan
