### ISSUE TITLE
[tdexdconnect] cert string is not the same as the one in filesystem

### ISSUE THREAD

**Issue by Janaka-Steph** [tdex-network/tdex-daemon#499]
If you compare cert from filesystem and cert string from `$ docker exec -it tdexd tdexdconnect --out url` you notice few differences:
`+` in FS becomes `-` in tdexdconnect string.
`/` in FS becomes `_`  in tdexdconnect string.

Finally cert string also missing the final `==`.

**Comment by Janaka-Steph** [comment]
This is what I do client side to download it and being installable.
Cert is installable only when tdexconnect string has been generated locally. I was not able to install cert from connect string of prod daemon at 3.250.80.165:9000.
![carbon](https://user-images.githubusercontent.com/4022128/141369402-ef3892b6-c92a-4c3b-9789-c37017c3e025.png)

**Comment by Janaka-Steph** [comment]
Digging a bit more I realise it's more tricky. Sometimes tdexdconnect string is missing final `==`, and sometimes the cert on FS doesn't have it. Because of this UI can't release a valid cert for sure.

**Comment by Janaka-Steph** [comment]
Well, actually if it's really necessary there may be a way to determine if and how many equals is necessary to be appended.
`A Base64 string will end with == if and only if the number of bytes it encodes, mod 3, equals 1.`
https://stackoverflow.com/questions/34211497/what-all-encryption-uses-in-the-last

**Comment by altafan** [comment]
tdexdconnect uses base64url encoding, while you are trying to decode it using the base64 std one.

Check this out to see the differences between the 2 encoding formats https://stackoverflow.com/questions/55389211/string-based-data-encoding-base64-vs-base64url.

Closing.
