### ISSUE TITLE
[UpdateMarketFixedFee] Error: fixed fee requires both base and quote amounts to be defined

### ISSUE THREAD

**Issue by Janaka-Steph** [tdex-network/tdex-daemon#501]
If setting only base or quote to value other than 0 an error `fixed fee requires both base and quote amounts to be defined` is returned. 
<img width="1025" alt="Screenshot 2021-11-12 at 13 14 27" src="https://user-images.githubusercontent.com/4022128/141473004-a2d989cf-ec50-4046-baa1-b8466e90d448.png">

**Comment by tiero** [comment]
ah-ha, I need we check for 0 to see if is nil/undefined on in interface/protobuf level, we should accpet 0/nil as valid isn't? @altafan

**Comment by altafan** [comment]
definitely
