### ISSUE TITLE
[ListTrades] gRPC returning empty array while cli returns trades

### ISSUE THREAD

**Issue by Janaka-Steph** [tdex-network/tdex-daemon#507]
<img width="792" alt="Screenshot 2021-11-19 at 16 16 47" src="https://user-images.githubusercontent.com/4022128/142655909-4db4105c-caef-4bcd-ba55-d4c169868d94.png">

<img width="641" alt="Screenshot 2021-11-19 at 16 19 02" src="https://user-images.githubusercontent.com/4022128/142656083-c1dadd64-89db-4018-a71b-6a97cb11e429.png">

**Comment by altafan** [comment]
try to remove `page`.

**Comment by tiero** [comment]
you calling the page number 20. This should maybe return error if number of trades is < of page_size
