### ISSUE TITLE
`tdex market fixedfee --base_fee 0 --quote_fee 0` ignores the 0 values

### ISSUE THREAD

**Issue by tiero** [tdex-network/tdex-daemon#521]
The UpdateMarketFixedFee seems to discard 0 values as if the protobuf request is empty. Those should be instead used as valid values﻿

**Comment by altafan** [comment]
Ah! This is tricky:
- originally, there was only a fixed fee for both assets
- then, we introduced base and quote fixed fees. With this change, the 0 value is used to actually ignore the change to let the user be able to update only one between the base and quote fees. For instance,  to update the quote fee one would call `market.ChangeFixedFees(0, 100)`. The fixed fees of the market cannot be zeroed with this design though.

I would add a new special value `-1` to replace the `0` special case where one wants to update only one of the 2 fees and leaving the other one as it is.

**Comment by tiero** [comment]
I think is fine to say that when updating only one side, we simply overwrite the other with current value

usually clients do;

- GetMarketInfo
- Fill the inouts with current value
- Update Fee with values changed and old one fetched 

Fine tho to have this special case, most of the time not needed (we will overwrite from clients all the times unchanged values)
