### ISSUE TITLE
Fragmenter Market: It should be possible to deposit a single asset in the pair

### ISSUE THREAD

**Issue by tiero** [tdex-network/tdex-daemon#522]

**Comment by altafan** [comment]
What if we allow this **ONLY** if the market has non-zero balance? This way, the very first fragmentation must be done funds of both assets. The idea is to "force" the user to make at least one "full" deposit with both to make sure the market is properly funded the very first time. 

I agree with you that it would be nice to be able to make "partial" deposits. Better to give this opportunity once the market is funded though.

**Comment by tiero** [comment]
> if the market has non-zero balance
yes, makes sense
