### ISSUE TITLE
[GetMarketReport] Add option to request a report of trade volume and collected fees until a certain time

### ISSUE THREAD

**Issue by Janaka-Steph** [tdex-network/tdex-daemon#551]
The use case I am thinking about is to calculate the volume of trades. 
We should determine if this option allow requesting trades until a certain date/Unix time, and/or x days, x months, x years.

**Comment by tiero** [comment]
We can follow the same api spec of `tdexa` https://github.com/tdex-network/tdex-analytics/blob/master/api-spec/protobuf/tdexa/v1/analytics.proto#L78-L102

**Comment by tiero** [comment]
Another topic, may be interesting to expose this on the public Trader interface? We query now `Market`, `Balances` and `MarketPrice`, may be interesting to have also data about volumes already computed? ie. `MarketVolume`

**Comment by altafan** [comment]
I think it could be worth adding such a feature to the trade interface to let the public know some analytics about markets.
What kind of info related to trade txs should we disclose within this method? Only their txids?

**Comment by tiero** [comment]
> What kind of info related to trade txs should we disclose

I do think would be best to provide volume only, already computed at this point, is more for traders consumption.

So it can be called `Volumes` RPC and passing a `Market` as request along with a time frame and start/end, either predefined (last day, last thre months etc..) or custom range, should return the aggragated trading volume.

**Comment by tiero** [comment]
That being said, for the dahsbord purpose, would be nice to have some extra filtering anyway, so would leave this open?

**Comment by altafan** [comment]
Since the dashboard doesn't interact with the trade interface, what do you think about renaming the `GetMarketCollectedSwapFees` rpc to something like `GetMarketReport` accepting a time window like the one in tdex-analytics and returning both the report on the collected fees and the trade volume?

**Comment by tiero** [comment]
> Since the dashboard doesn't interact with the trade interface, what do you think about renaming the `GetMarketCollectedSwapFees` rpc to something like `GetMarketReport` accepting a time window like the one in tdex-analytics and returning both the report on the collected fees and the trade volume?

ACK! Much better also for the clients since it already calls in that page info about the volumes and the collected fees
