### ISSUE TITLE
ListWebhooks called with ALL_ACTIONS doesn't list any webhooks

### ISSUE THREAD

**Issue by Janaka-Steph** [tdex-network/tdex-daemon#560]

**Comment by sekulicd** [comment]
There are multiple event-types that someone can subscribe to:
```
TRADE_SETTLED = 0;
ACCOUNT_LOW_BALANCE = 1;
ACCOUNT_WITHDRAW = 2;
ALL_ACTIONS = 3; (meaning send me notification when ever occurs any of event above) 
```
In that sense tdex-daemon treats ALL_ACTIONS as a type and it is not filter that says give me all webhooks.
So ListWebhooks called with ALL_ACTIONS doesnt means give me all webhooks but, give me webhooks of type ALL_ACTIONS, and i guess u didnt created such webhook before u invoke endpoint.
