### ISSUE TITLE
Request to unlock with password on Withdraw RPCs

### ISSUE THREAD

**Issue by tiero** [tdex-network/tdex-daemon#563]

**Comment by tiero** [comment]
Do you think this fits the flow with ocean/gdks backends?

**Comment by tiero** [comment]
Also this for next release @altafan

**Comment by altafan** [comment]
Ocean's [RPC](https://github.com/vulpemventures/ocean/blob/master/api-spec/protobuf/ocean/v1/transaction.proto#L226-L237) doesn't support this at the moment. Let's open the same ticket in that project.

For gdk-ocean, if that's not supported natively by the apis, we can just manually add this security layer.

In conclusion i think it fits ocean/gdk backends.

> Also this for next release @altafan

Does this imply next release must include wallet detachment?

**Comment by tiero** [comment]
Can we quickly add it as an extra security measure ie. if the password passed in RPC does NOT decrypt the vault, we interrupt the withdrawal processs
