### ISSUE TITLE
[GetInfo] Return daemon fixed assets

### ISSUE THREAD

**Issue by Janaka-Steph** [tdex-network/tdex-daemon#565]
Environment variables `TDEX_BASE_ASSET` fixes the base asset, `TDEX_QUOTE_ASSET` fixes the quote asset.
Return this info in `GetInfo` so that clients can display this information to the operator.

**Comment by tiero** [comment]
What about returning the full configuarion (ie. viper ENV VAR) in `GetInfo` or a new `GetConfig` RPC? @sekulicd @altafan

**Comment by altafan** [comment]
`GetConfig` would return info out of the scope of its service (`WalletService`) considering that the full configuration includes things like the datadir, TLS/macaroons location, the profiler stats interval, and so on. I'm not even sure what's the advantage for the operator to retrieve the configs via rpc.
Rather, I do think it could be useful for him to know what's the daemon's fixed asset, as @Janaka-Steph proposed.

Instead, I do think it would be fine to add the fixed base/quote asset to `GetInfo`'s reply for the reason
