### ISSUE TITLE
[grpc-web] Http error at 400 or 500 level

### ISSUE THREAD

**Issue by Janaka-Steph** [tdex-network/tdex-daemon#584]
We observe that requests may fail with error `Http error at 400 or 500 level`. 
It seems that connection is dropped after around 15 minutes.

**Comment by Janaka-Steph** [comment]
Maybe something to follow https://github.com/grpc/grpc-node/issues/2046

**Comment by tiero** [comment]
> It seems that connection is dropped after around 15 minutes.

Do you mean during streaming calls?  gRPC does not keep persistent TCP channel in unary calls, only streaming I guess.

Also which client you using? browsers? the daemon is local or remote? exposed via docker or binary?

**Comment by Janaka-Steph** [comment]
I am using web clients. Issue should be specific to `grpc-web`
