### ISSUE TITLE
Drop OperatorService.GetMarketBalance? 

### ISSUE THREAD

**Issue by altafan** [tdex-network/tdex-daemon#601]
In operator.proto we have 2 methods that look a bit redundant: [`GetMarketBalance`](../blob/master/api-spec/protobuf/tdex-daemon/v1/operator.proto#L47) is basically a subset of [`GetMarketInfo`](../blob/master/api-spec/protobuf/tdex-daemon/v1/operator.proto#L36). Could be worth dropping `GetMarketBalance`?

**Comment by tiero** [comment]
Looks good to me, nor priority tho

Please share your thoughts @sekulicd

**Comment by sekulicd** [comment]
ACK

**Comment by altafan** [comment]
@sekulicd can you make sure of the impact of this for tdex-dashboard?

**Comment by sekulicd** [comment]
Its true that GetMarketBalance is subset of GetMarketInfo, note that GetMarketInfo returns only unlocked balance while  GetMarketBalance returns both locked and unlocked.

Removing GetMarketBalance would mean we need to:
1. Update tdex-dashbord where GetMarketBalance is used in [here](https://github.com/tdex-network/tdex-dashboard/blob/master/src/features/operator/Market/MarketWithdraw/index.tsx#L53) and [here](https://github.com/tdex-network/tdex-dashboard/blob/master/src/features/operator/Market/MarketOverview/index.tsx#L30)
2. Update tdex-analytics where GetMarketBalance is used in [here](https://github.com/tdex-network/tdex-analytics/blob/72c25971bf3202b16f3e310148de34ffa02dddeb/pkg/tdex-market-loader/client.go#L87)

**Comment by altafan** [comment]
it seems to me that 2) is actually using GetMarketBalance from TradeService, not from OperatorService.

I think it's better to do this when detaching the wallet then, when we introduce operator/v2 protos.

**Comment by altafan** [comment]
done in v1.
