### ISSUE TITLE
Mismatch between GetMarketCollectedSwapFeesResponse and MarketReport

### ISSUE THREAD

**Issue by Janaka-Steph** [tdex-network/tdex-daemon#604]
@altafan 
GetMarketCollectedSwapFeesResponse and MarketReport don't return the same swap fees amounts.
 
GetMarketCollectedSwapFeesResponse.getTotalCollectedFeesPerAssetMap()
<img width="630" alt="Screenshot 2022-06-09 at 16 45 07" src="https://user-images.githubusercontent.com/4022128/172896136-7f074992-4de3-4e17-b636-38211fdc1e8d.png">

0,00733747 L-BTC === $222,05 (today)
231,61589814 USDt

But marketReport.totalCollectedFees gives different amounts
<img width="362" alt="Screenshot 2022-06-09 at 16 49 21" src="https://user-images.githubusercontent.com/4022128/172896344-13a84bb8-e594-47d7-ae0f-1ccfa0686ca5.png">
0,00030721 L-BTC === $9,2696 
2,11797530 USDt

**Comment by Janaka-Steph** [comment]
@altafan @tiero That was it indeed. In Dashboard the Collected Swap Fees amounts depends on predefined period. I don't think it is intuitive, I would rather show the total. 

However, sorry guys, I found an other bug. PREDEFINED_PERIOD_ALL is stoping at previous calendar year. I am missing all 2022 data points.

**Comment by altafan** [comment]
Can you provide data of a real example in order for us to track down the bug and its fix?

cc @sekulicd

**Comment by Janaka-Steph** [comment]
You can check getMarketReport() with daemon `tdexdconnect://54.217.30.13:9000`
