### ISSUE TITLE
PREDEFINED_PERIOD_ALL is stoping at previous calendar year

### ISSUE THREAD

**Issue by Janaka-Steph** [tdex-network/tdex-daemon#605]
All 2022 data points are missing.

**Comment by Janaka-Steph** [comment]
Sorry for the poor issue. I was probably refering to testnet env.

**Comment by Janaka-Steph** [comment]
I dont have my computer now. I will check when I am back :)

**Comment by Janaka-Steph** [comment]
@sekulicd Still the case on testnet (provider.tdex.network:29000).
Predifined period == ALL, timeframe == Week
You can see it stops at 31/12/2021

<img width="1471" alt="Screenshot 2022-08-08 at 14 40 07" src="https://user-images.githubusercontent.com/4022128/183420362-c41d3e44-a37c-420d-bc99-a70da1dc7434.png">

**Comment by tiero** [comment]
Updated to 0.8.14

**Comment by tiero** [comment]
We are still experiencing this https://www.loom.com/share/df1c0bbe8632404cb6bde47c11a8d5e8
