### ISSUE TITLE
tdexdconnect: weird host:port validation

### ISSUE THREAD

**Issue by tiero** [tdex-network/tdex-daemon#607]
I am trying to test TLS self signed combination via ngrok locally (ie. `ngrok tcp 9000`) and I noticed that passing to `--rpcserver` either port :80/:443 or sub-domain starting with a number like `2.tcp.eu.ngrok.io:18240` will throw `rpcserver host is invalid`

**Comment by altafan** [comment]
@tiero is this still  a bug?

**Comment by tiero** [comment]
Yep!

**Comment by sekulicd** [comment]
I managed to get correct tdexdconnect url using https, started ngrok with `ngrok http https://localhost:9000`
For grpc ngrok.yml needs to be configured:
```
tunnels:
  grpc:
    proto: tcp
    addr: 9000
    inspect: false
```
and then `ngrok start grpc`, after i tried to connect to the daemon using cli i got:
"transport: authentication handshake failed: x509: certificate is valid for dusans-MacBook-Pro.local, localhost, unix, unixpacket, not 5.tcp.eu.ngrok.io"

Regarding error @tiero was getting it is related to [this](https://github.com/tdex-network/tdex-daemon/blob/391fc3d4c52c761c1fc50f197fef517ba0db47e4/cmd/tdexdconnect/main.go#L95) validation.

**Comment by tiero** [comment]
ok but beside the ngrok stuff,  `tdexdconnect` should accept `2.tcp.eu.ngrok.io:18240` domain as valid no?

**Comment by tiero** [comment]
> > ok but beside the ngrok stuff, tdexdconnect should accept 2.tcp.eu.ngrok.io:18240 domain as valid no?
> 
> [This](https://github.com/tdex-network/tdex-daemon/blob/f63c71f5e7c716bbb4a6b4d29fe6ef96e962fe0e/cmd/tdexdconnect/main.go#L50) regex doesnt allows digit at first position in domain.

I think thats' wrong indeed
