### ISSUE TITLE
panic on InitWallet restore:true with passphrase different than TDEX_WALLET_UNLOCK_PASSWORD_FILE set

### ISSUE THREAD

**Issue by tiero** [tdex-network/tdex-daemon#612]
```
time="2022-08-02T21:32:17Z" level=info msg="All 0 tables opened in 0s\n"
time="2022-08-02T21:32:17Z" level=info msg="Replaying file id: 0 at offset: 0\n"
time="2022-08-02T21:32:17Z" level=info msg="Replay took: 41.201µs\n"
time="2022-08-02T21:32:17Z" level=info msg="All 0 tables opened in 0s\n"
time="2022-08-02T21:32:17Z" level=info msg="Replaying file id: 0 at offset: 0\n"
time="2022-08-02T21:32:17Z" level=info msg="Replay took: 4.801µs\n"
time="2022-08-02T21:32:17Z" level=info msg="All 0 tables opened in 0s\n"
time="2022-08-02T21:32:17Z" level=info msg="Replaying file id: 0 at offset: 0\n"
time="2022-08-02T21:32:17Z" level=info msg="Replay took: 4.803µs\n"
time="2022-08-02T21:32:17Z" level=info msg="rescan internal wallet's utxo set. This could take a while..."
time="2022-08-02T21:32:17Z" level=debug msg="Restored uspents: 0"
time="2022-08-02T21:32:17Z" level=debug msg="Restore took: 0.00s"
time="2022-08-02T21:32:17Z" level=info msg=done
time="2022-08-02T21:32:17Z" level=info msg="starting daemon"
time="2022-08-02T21:32:17Z" level=info msg="wallet unlocker interface is listening on :9000"
time="2022-08-02T21:32:17Z" level=debug msg="stop grpc-web Operator server"
time="2022-08-02T21:32:17Z" level=debug msg="stop grpc Operator server"
time="2022-08-02T21:32:17Z" level=debug msg="stop mux Operator"
panic: passphrase provided is not correct

goroutine 121 [running]:
github.com/tdex-network/tdex-daemon/internal/interfaces/grpc.(*service).startListeningToReadyChan(0xc010334000)
	/home/runner/work/tdex-daemon/tdex-daemon/internal/interfaces/grpc/service.go:482 +0x3d0
created by github.com/tdex-network/tdex-daemon/internal/interfaces/grpc.(*service).Start
	/home/runner/work/tdex-daemon/tdex-daemon/internal/interfaces/grpc/service.go:277 +0x10a
time="2022-08-02T21:32:47Z" level=info msg="All 0 tables opened in 0s\n"
time="2022-08-02T21:32:47Z" level=info msg="Replaying file id: 0 at offset: 0\n"
time="2022-08-02T21:32:47Z" level=info msg="Replay took: 34.603µs\n"
time="2022-08-02T21:32:47Z" level=info msg="All 0 tables opened in 0s\n"
time="2022-08-02T21:32:47Z" level=info msg="Replaying file id: 0 at offset: 0\n"
time="2022-08-02T21:32:47Z" level=info msg="Replay took: 4.78µs\n"
time="2022-08-02T21:32:47Z" level=info msg="All 0 tables opened in 0s\n"
time="2022-08-02T21:32:47Z" level=info msg="Replaying file id: 0 at offset: 0\n"
time="2022-08-02T21:32:47Z" level=info msg="Replay took: 9.42µs\n"
time="2022-08-02T21:32:47Z" level=info msg="rescan internal wallet's utxo set. This could take a while..."
time="2022-08-02T21:32:47Z" level=debug msg="Restored uspents: 0"
time="2022-08-02T21:32:47Z" level=debug msg="Restore took: 0.00s"
time="2022-08-02T21:32:47Z" level=info msg=done
time="2022-08-02T21:32:47Z" level=info msg="starting daemon"
time="2022-08-02T21:32:47Z" level=info msg="wallet unlocker interface is listening on :9000"
time="2022-08-02T21:32:47Z" level=debug msg="stop grpc-web Operator server"
time="2022-08-02T21:32:47Z" level=debug msg="stop grpc Operator server"
time="2022-08-02T21:32:47Z" level=debug msg="stop mux Operator"
panic: passphrase provided is not correct

goroutine 97 [running]:
github.com/tdex-network/tdex-daemon/internal/interfaces/grpc.(*service).startListeningToReadyChan(0xc00062c480)
	/home/runner/work/tdex-daemon/tdex-daemon/internal/interfaces/grpc/service.go:482 +0x3d0
created by github.com/tdex-network/tdex-daemon/internal/interfaces/grpc.(*service).Start
	/home/runner/work/tdex-daemon/tdex-daemon/internal/interfaces/grpc/service.go:277 +0x10a
```

**Comment by tiero** [comment]
Scenario: the daemon already had a `TDEX_WALLET_UNLOCK_PASSWORD_FILE` setup with password X, I tried instead to INitWallet passing password Y

**Comment by altafan** [comment]
the problem is [here](https://github.com/tdex-network/tdex-daemon/blob/master/internal/interfaces/grpc/service.go#L483). We intentionally panic, not sure the reason but should be changed with a warning message. The operation shouldn't be repeated after the first failed attempt I think.

**Comment by sekulicd** [comment]
@tiero @altafan should we maybe ignore this error and delete pass file if this happens?

**Comment by sekulicd** [comment]
@tiero @altafan 
I think we need to rethink behavior of this feature:
1. Where do we use unlocking with pass file? I think we should move it in [here](https://github.com/tdex-network/tdex-daemon/blob/f63c71f5e7c716bbb4a6b4d29fe6ef96e962fe0e/internal/core/application/walletunlocker_service.go#L192)?
2. What should be behaviour when InitWallet/ChangePass RPCs are invoked? do we give priority to password from file or to passed pass through RPC, do we update pass in file in that scenario?

**Comment by tiero** [comment]
I guess we should handle the panic and log an error. maybe any action such as init or unlock should return explicitly "UNLOCKER PASSWORD different than given password"

**Comment by altafan** [comment]
> Where do we use unlocking with pass file? I think we should move it in [here](https://github.com/tdex-network/tdex-daemon/blob/f63c71f5e7c716bbb4a6b4d29fe6ef96e962fe0e/internal/core/application/walletunlocker_service.go#L192)?

I don't think we need to focus on refactoring the code, instead, we should stop to panic intentionally in case of errors, like done [here](https://github.com/tdex-network/tdex-daemon/blob/master/internal/interfaces/grpc/service.go#L523-L525) or [here](https://github.com/tdex-network/tdex-daemon/blob/master/internal/interfaces/grpc/service.go#L537).

In general, it's not a good idea to panic if we don't take care of recovering from it, and there are no other parts of the code where we explicitly panic from code.

If the auto-unlock fails, for now, it's enough to print a warning on stdout and just don't stop the execution. The operator will take care of manually unlocking the wallet.

**Comment by altafan** [comment]
> What should be behaviour when InitWallet/ChangePass RPCs are invoked? do we give priority to password from file or to passed pass through RPC, do we update pass in file in that scenario?

Changing the password requires the daemon to be locked, so ATM the operator has to stop it, disable auto-unlocking (remove env var), restart it, and change the password. Only after all this, he can enable the auto-unlocking again.

In conclusion, we don't need to give any priority because the 2 things are in someway mutually exclusive.
