### ISSUE TITLE
tdexdconnect: Support TLS termination with CA signed certificate

### ISSUE THREAD

**Issue by tiero** [tdex-network/tdex-daemon#622]
## Overview 

In some scenarios, the daemon could be deployed in a context where the TLS termination is already present (ie. from a reverse proxy on top) therefore it conflicts with the self-signed certificate of the operator interface.

We now can disable the generation of TLS self-signed via `TDEX_NO_OPERATOR_TLS` env var, but this makes generating tdexdconnect URLS like 

`tdexdconnect://<host>:<port>` if not initialized and `tdexdconnect://<host>:<port>?macaroon=` after seed has been init without the `cert` field.

We need to think of a way to communicate this to clients such as CLI or dashboard, in a way the client knows to use secure connection, but leave to the http client used to make the TLS handshake correctly.

## Proposal
One idea could be to introduce a new field in the query string such as `?proto=http` or `?proto=https` ?  

#### Validation/Behavior
- If the `?cert` has been given already we default to `https` and ignore anything given to the proto field ? 
- or we return error if `cert` is given, but anything beside `https` inside the `proto` field is passed?

@Janaka-Steph @sekulicd @louisinger

**Comment by tiero** [comment]
Some more thoughts on the topic

https://docs.lightning.engineering/lightning-network-tools/lightning-terminal/lightning-node-connect

**Comment by tiero** [comment]
any comment about my proposal? What about validation behavior? @altafan

**Comment by Janaka-Steph** [comment]
Can you explain why proto is an array? Why not `https` or `http`?
Why having `proto`? Could be if `cert` is given then https, if not then http?

**Comment by tiero** [comment]
> Can you explain why proto is an array? Why not `https` or `http`?

yeah it means "one of" in that array, yes the `proto` must be EITHER `https` or `http

> Why having proto? Could be if cert is given then https, if not then http?

If cert is not given, it could be because the operator server is exposed with TLS signed by Certificate Authority

**Comment by tiero** [comment]
> must be set by the user when generating the URL

Yes exactly should be a parameter. 

We can only infer the proto is `https` if the `cert` is passed, but this is linked on the validation behavior: either fail always if user dont give us all param explicitly or we add some implicit logic

**Comment by tiero** [comment]
re: daemon

we can add the following env vars to generate the right tdexdconnect URL generated by the daemon fot the HTML page

- `TDEX_CONNECT_HOST` ie. `mydomain.com:443` or `10.10.10.0:9000`
- `TDEX_CONNECT_PROTO` ie. `https` or `http`

This are used in combination with already existent config variables

- `TDEX_NO_MACAROONS` to remove the `?macaroon` param
- `TDEX_NO_OPERATOR_TLS` to remove the `?cert` param

**Comment by altafan** [comment]
I agree, but I also suggest making tdexdconnect an RPC of the daemon rather than a dedicated service. This way we could take advantage of the daemon's configuration to determine what needs to be included in the connect url.

**Comment by tiero** [comment]
I think the best validation behavior should be

- if `cert` is given and `proto` is  not set, valid ✅ (we default to `https` in clients)
- if `cert` is given and `proto` is set to http, we return error ⛔️
- if `cert` is NOT given and `proto` is set to `https` we assume a CA signed certificate is setup

cc/ @Janaka-Steph can you create corrsponding task on `tdex-dashboard`?

**Comment by Janaka-Steph** [comment]
Sure!

**Comment by altafan** [comment]
Take into account that at the moment tdexdconnect always inlcudes a `cert` param in the generated URL unless the `--insecure` flag is passed when running the command. By default it looks for the TLS cert into the daemon's datadir but it can be overwritten with the `--tls_cert_path` flag.

Given the changes to the Operator interface's auth, we may need to replace `--insecure` with 2 new flags `--no-tls` and `--no-macaroons` to include/exclude either `cert` or `macaroon`.

**Comment by altafan** [comment]
> but I also suggest making tdexdconnect an RPC of the daemon rather than a dedicated service

Bad suggestion. There would be no way to protect that RPC, even with the wallet password, because it has to be accessible even before the wallet is initialized. Let's keep things as they are.
