### ISSUE TITLE
Requesting daemon without port replies something

### ISSUE THREAD

**Issue by Janaka-Steph** [tdex-network/tdex-daemon#628]
Calling `https://tdexd.sevenlabs.ninja/tdex_daemon.v1.OperatorService/GetInfo`
Replies `{"code":5, "message":"Not Found", "details":[]}`

Not sure if it's a bug but I would expect the server to not reply and terminate with `ERR_CONNECTION_TIMED_OUT`

**Comment by tiero** [comment]
This wont work, since you making a GET HTTP 1.1 call on that interface.

Doing a grpcweb call (POST) works fine to me

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/3596602/187245980-243808aa-70b6-48b8-ad3a-e414136e554b.png">
