### ISSUE TITLE
Calling the GET /v1/transport does not returns the response

### ISSUE THREAD

**Issue by tiero** [tdex-network/tdex-daemon#632]
```
curl --location --request GET 'https://stage-tdexd.sevenlabs.ninja/v1/transport' \
--header 'Content-Type: application/json' \
--data-raw '{}'
```

**Comment by altafan** [comment]
How the daemon is served? interfaces on different ports or same port?

We have some bugs to fix for both cases:
* different port, the transport handler is [registered](https://github.com/tdex-network/tdex-daemon/blob/0151a86432827a96af57b0cc85778e87da94b4e6/internal/interfaces/grpc/service.go#L345-L346) on the operator interface for which we don't want to support grpc gateway. It must be registered on the trade one instead.
* same port, we are missing to [register](https://github.com/tdex-network/tdex-daemon/blob/0151a86432827a96af57b0cc85778e87da94b4e6/internal/interfaces/grpc/service_one_port.go#L359-L361) the transport handler on the grpc gateway to let it proxy its RPCs
