### ISSUE TITLE
[tdexconnect] Enable CORS 

### ISSUE THREAD

**Issue by altafan** [tdex-network/tdex-daemon#634]
I tried to run the dashboard (from browser) and pair it with an insecure daemon (v0.8.15) via tdexdconnect url but there's a connection issue and the request fails with error:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:9000/tdexdconnect. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 404.
```

At the moment, the daemon's internal routing handler dispatch requests to grpc-gateway server only if they are `GET` or contain `Content-Type: application/json` header, but we should allow also CORS

**Comment by tiero** [comment]
GET request have no CORS restrictions, only POST do.

But yes never noticed because usually I served tdex daemons under https

**Comment by altafan** [comment]
In general, all requests are preceded by an OPTION one and we don't have any check for this in our [router](https://github.com/tdex-network/tdex-daemon/blob/master/internal/interfaces/grpc/http_utils.go#L285-L309).

Not sure that enabling/disabling TLS does make any difference actually.
