### ISSUE TITLE
Add CORS headers to http responses

### ISSUE THREAD

**Issue by altafan** [tdex-network/tdex-daemon#638]
At the moment, the daemon adds CORS headers only to [pre-flight responses](https://github.com/tdex-network/tdex-daemon/blob/master/internal/interfaces/grpc/http_utils.go#L286-L288) while it should do the same also for [GET responses](https://github.com/tdex-network/tdex-daemon/blob/master/internal/interfaces/grpc/http_utils.go#L291-L293) and for [grpc-gateway endpoints](https://github.com/tdex-network/tdex-daemon/blob/master/internal/interfaces/grpc/http_utils.go#L303-L305).

**Comment by tiero** [comment]
I guess also POST request, to support HTTP JSON content type for the trader interface

**Comment by altafan** [comment]
Yes, those endpoints are handled by the grpc gateway internal proxy (the last link of the description)
