### ISSUE TITLE
Daemon process hangs on error

### ISSUE THREAD

**Issue by sekulicd** [tdex-network/tdex-daemon#651]
Using bellow env vars will cause error thrown by TdexConnectService:
TDEX_BASE_ASSET=5ac9f65c0efcc4775e0baec4ec03abdde22473cd3cf33c0419ca290e0751b225
TDEX_CRAWL_INTERVAL=50000000000
TDEX_ENABLE_PROFILER=true
TDEX_EXPLORER_ENDPOINT=http://127.0.0.1:3001
TDEX_LOG_LEVEL=5
TDEX_NETWORK=regtest
TDEX_CONNECT_PROTO=http

I was expecting daemon to shut down but process is hanging, PSB:
<img width="891" alt="Screen Shot 2022-10-10 at 12 51 14" src="https://user-images.githubusercontent.com/1805417/194850678-130e2589-0646-4140-bb03-aaf8efcb9ab9.png">

**Comment by tiero** [comment]
Could be the profiler failing to shutdown gracefully?

**Comment by sekulicd** [comment]
> Could be the profiler failing to shutdown gracefully?

I am actually not sure what is hanging in the background and why.
However, [this](https://github.com/tdex-network/tdex-daemon/pull/652) makes sure process is killed.

**Comment by altafan** [comment]
The reason has been explained [here](https://github.com/tdex-network/tdex-daemon/pull/652#issuecomment-1273397517). Soon crawler/bc listener will be dropped with wallet detachment (WIP, almost ready) therefore this can be closed.
