### ISSUE TITLE
http web: Show Operator & Trader endpoints QRCode(s) 

### ISSUE THREAD

**Issue by tiero** [tdex-network/tdex-daemon#656]
We should add a switch component in the UI to switch different connection URLs

- For operators to connect the Dashboard & CLI to, the `tdexdconnect` URL
- For traders to add to their Mobile App or any other trader web client, the trader endpoint ie. `https://tdex.provider:9945`

**Comment by tiero** [comment]
We should have a ENV VAR like for TDEX_CONNECT_ADDR to know the public reachable endpoint and print on the page? (ie. to add to your mobile app just scanning) @altafan

**Comment by altafan** [comment]
> We should have a ENV VAR like for TDEX_CONNECT_ADDR to know the public reachable endpoint and print on the page? 

Yes. What about `TDEX_TRADING_ADDR`? 

> We should add a switch component in the UI to switch different connection URLs

I didn't really understand who's the actor that wants to retrieve the trading endpoint. The operator? The trader? Both?

**Comment by Janaka-Steph** [comment]
I would have call it PUBLIC_ENDPOINT. 
I suppose it's useful for the operator to check that its daemon is correctly set up. 
A trader can't access this page without login.

**Comment by altafan** [comment]
Thanks.

We also need the operator interface to expose an endpoint just like done for the connect URL.
What do you think of `/trading` as name?

**Comment by Janaka-Steph** [comment]
Imho I would call it /public-endpoint hehe

**Comment by tiero** [comment]
> I didn't really understand who's the actor that wants to retrieve the trading endpoint.

Yes it's more the operator, to be able to test it out, since who setup the daemon in the infra (ie. set the ENV VAR etc..) may not be the same as who has setup the wallet/password etc...

> call it PUBLIC_ENDPOINT

We have everywhere the concept of "Trade" and "Trader" interface vs the "Operator" interface. 
Both are public endpoints, just the former is non-authenticated and the latter  could (maybe) have macaroons as auth method.


I vouch for `TDEX_TRADER_ADDR` and for `/trader` endpoint
