### ISSUE TITLE
 Getting `GetMarketReport failure - RpcError: not implemented`, method seems missing.

### ISSUE THREAD

**Issue by tiero** [tdex-network/tdex-daemon#658]
- Getting `GetMarketReport failure - RpcError: not implemented`, method seems missing.

- Getting `ListTrades failure - RpcError: Skip must be set to a positive number` if `page: { number: 0, size: 5 }`. Number should be at least 1. What should be the behaviour of `number: 0`? Error message should be more explicit.

_Originally posted by @Janaka-Steph in https://github.com/tdex-network/tdex-daemon/issues/655#issuecomment-1337582862_

**Comment by altafan** [comment]
Refers to daemon w/ detached wallet. Closing since it's beenalready fixed in the PR
