### ISSUE TITLE
[v2] InitWallet returns NOT_FOUND

### ISSUE THREAD

**Issue by Janaka-Steph** [tdex-network/tdex-daemon#661]
Calling  InitWallet returns NOT_FOUND.
```
const { data } = await initWallet({
    restore: true,
    password: state.password,
    seedMnemonic: wordsArray as string[],
});
```

**Comment by tiero** [comment]
From master or form a tagged release?

**Comment by Janaka-Steph** [comment]
From master

**Comment by Janaka-Steph** [comment]
Now I am getting `missing birthday block height`

**Comment by altafan** [comment]
In master there's no proto v2 though. I guess you are either running altafan/detach-wallet or v1.0.0-rc.0?

**Comment by Janaka-Steph** [comment]
Oh yes I meant building from detach-wallet branch

**Comment by altafan** [comment]
restoring a wallet is not currently supported.
