### ISSUE TITLE
[v1] GetMarketReport 1 year timeframe is wrong

### ISSUE THREAD

**Issue by Janaka-Steph** [TDex-network/tdex-daemon#695]
Start date should be now - 1 year

<img width="801" alt="Screenshot 2023-04-04 at 18 51 51" src="https://user-images.githubusercontent.com/4022128/229865750-36a6e2c8-5c56-4815-93ae-122d6834aad8.png">

**Comment by altafan** [comment]
Year timeframe returns the frame for the past year, so at the time of writing would be the whole 2022.
YearToDate returns the frame [startOfCurrentYear, now].

You can use a custom period to cover the period [now, now - 1 year].
