### ISSUE TITLE
[v1] NewMarketRequest.name should be optional

### ISSUE THREAD

**Issue by Janaka-Steph** [TDex-network/tdex-daemon#696]

**Comment by altafan** [comment]
At the moment the name of a market cannot be set manually, it's automatically generated as hash of base asset+quote asset.
There's already an open PR on Ocean to allow the operator to assign a friendly name to an account, while a unique namespace is set automatically. One can ref to an account via Namespace or Name at will.

On the daemon side, this means a market will be referenced via its assets, friendly name, or the assigned namespace.

**Comment by altafan** [comment]
closed by #685
