### ISSUE TITLE
[v1] GetMarketInfo - incorrect totalBalance

### ISSUE THREAD

**Issue by Janaka-Steph** [TDex-network/tdex-daemon#700]
<img width="982" alt="Screenshot 2023-04-17 at 15 54 31" src="https://user-images.githubusercontent.com/4022128/232505826-0aa10fca-891e-4f76-9524-a36964276061.png">

I notice after a withdraw that balance.totalBalance is incorrect.
balance.totalBalance is computed as the sum of unconfirmedBalance and lockedBalance, but this is incorrect since the same coins are counted twice.

**Comment by altafan** [comment]
which balance do you refer to? base, quote, or both?

The amounts returned do not seem wrong to me though:
* on base asset, there's a 1 BTC confirmed balance, the rest is 0 so 1 BTC total
* on quote asset, there's 19980 USDT unconfirmed, 0 confirmed and 19990 locked, so 39970 USDT total

**Comment by Janaka-Steph** [comment]
Referring to the quote ac3...
I had 19990 and withdraw 10. I have 19980 left. I never had 39970. 
What do we mean by totalBalance? Maybe I don't interpret this field properly?

**Comment by Janaka-Steph** [comment]
Also the daemon is slow to confirm balances. Refetching GetMarketInfo 10 seconds after withdraw is not enough, confirmed balance is still zero.

**Comment by altafan** [comment]
can you make another test and share the balance response before and after the withdrawal?

**Comment by Janaka-Steph** [comment]
Same behaviour.

Before
<img width="781" alt="Screenshot 2023-04-20 at 16 12 16" src="https://user-images.githubusercontent.com/4022128/233394056-7b5a8d95-24a8-45fa-a7bb-ac02a50b239b.png">

After
<img width="810" alt="Screenshot 2023-04-20 at 16 14 27" src="https://user-images.githubusercontent.com/4022128/233394115-1ab75641-76bf-461d-91f4-14cca98557d5.png">

**Comment by altafan** [comment]
This must be fixed by ocean.
