### ISSUE TITLE
Some funds locked in a market.

### ISSUE THREAD

**Issue by plimdim** [TDex-network/tdex-daemon#719]
I am trying to empty a market to delete it. But it has some funds locked. I don't know why.
I could withdraw my asset. But I can't move the remaining L-BTC on that market.

```
./tdex market balance
{
        "available_balance": {
                "base_amount": "11767",
                "quote_amount": "0"
        },
        "total_balance": {
                "base_amount": "31767",
                "quote_amount": "0"
        }
}
```

And I also receive this message on the dashboard when trying to withdraw the remaining L-BTC on that market. 

![12-Jun-2023-215100_1920x1040 png_cropped](https://github.com/tdex-network/tdex-daemon/assets/109290211/f5ecca47-d511-4168-b053-dcb1894267fb)

![12-Jun-2023-214434_1920x1040 png_cropped](https://github.com/tdex-network/tdex-daemon/assets/109290211/f1390009-1c63-4786-8264-644c0294c891)

![12-Jun-2023-214831_1920x1040 png_cropped](https://github.com/tdex-network/tdex-daemon/assets/109290211/1a226cdc-3b3c-4f60-9465-cae3f5c74183)

**Comment by tiero** [comment]
@altafan can followup offline with DM
